// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:GeofenceLocationCollection.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// GeofenceLocationCollection TABLE
class TableGeofenceLocationCollection extends SqfEntityTableBase {
  TableGeofenceLocationCollection() {
    // declare properties of EntityTable
    tableName = 'geofenceLocationCollection';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('uuid', DbType.text, isNotNull: false),
      SqfEntityFieldBase('radius', DbType.real, isNotNull: false),
      SqfEntityFieldBase('latitude', DbType.real, isNotNull: false),
      SqfEntityFieldBase('longitude', DbType.real, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableGeofenceLocationCollection();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class DatabaseModel extends SqfEntityModelProvider {
  DatabaseModel() {
    databaseName = databaseModel.databaseName;
    password = databaseModel.password;

    databaseTables = [
      TableGeofenceLocationCollection.getInstance,
    ];

    bundledDatabasePath = databaseModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region GeofenceLocationCollection
class GeofenceLocationCollection {
  GeofenceLocationCollection(
      {this.id, this.uuid, this.radius, this.latitude, this.longitude}) {
    _setDefaultValues();
  }
  GeofenceLocationCollection.withFields(
      this.uuid, this.radius, this.latitude, this.longitude) {
    _setDefaultValues();
  }
  GeofenceLocationCollection.withId(
      this.id, this.uuid, this.radius, this.latitude, this.longitude) {
    _setDefaultValues();
  }
  GeofenceLocationCollection.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['uuid'] != null) {
      uuid = o['uuid'] as String;
    }
    if (o['radius'] != null) {
      radius = double.tryParse(o['radius'].toString());
    }
    if (o['latitude'] != null) {
      latitude = double.tryParse(o['latitude'].toString());
    }
    if (o['longitude'] != null) {
      longitude = double.tryParse(o['longitude'].toString());
    }
  }
  // FIELDS (GeofenceLocationCollection)
  int id;
  String uuid;
  double radius;
  double latitude;
  double longitude;

  BoolResult saveResult;
  // end FIELDS (GeofenceLocationCollection)

  static const bool _softDeleteActivated = false;
  GeofenceLocationCollectionManager __mnGeofenceLocationCollection;

  GeofenceLocationCollectionManager get _mnGeofenceLocationCollection {
    return __mnGeofenceLocationCollection =
        __mnGeofenceLocationCollection ?? GeofenceLocationCollectionManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (uuid != null) {
      map['uuid'] = uuid;
    }

    if (radius != null) {
      map['radius'] = radius;
    }

    if (latitude != null) {
      map['latitude'] = latitude;
    }

    if (longitude != null) {
      map['longitude'] = longitude;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (uuid != null) {
      map['uuid'] = uuid;
    }

    if (radius != null) {
      map['radius'] = radius;
    }

    if (latitude != null) {
      map['latitude'] = latitude;
    }

    if (longitude != null) {
      map['longitude'] = longitude;
    }

    return map;
  }

  /// This method returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [uuid, radius, latitude, longitude];
  }

  List<dynamic> toArgsWithIds() {
    return [id, uuid, radius, latitude, longitude];
  }

  static Future<List<GeofenceLocationCollection>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR GeofenceLocationCollection.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<GeofenceLocationCollection>> fromJson(
      String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <GeofenceLocationCollection>[];
    try {
      objList = list
          .map((geofencelocationcollection) =>
              GeofenceLocationCollection.fromMap(
                  geofencelocationcollection as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print(
          'SQFENTITY ERROR GeofenceLocationCollection.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<GeofenceLocationCollection>> fromMapList(
      List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<GeofenceLocationCollection> objList =
        <GeofenceLocationCollection>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = GeofenceLocationCollection.fromMap(
          map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns GeofenceLocationCollection by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns GeofenceLocationCollection if exist, otherwise returns null
  Future<GeofenceLocationCollection> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    GeofenceLocationCollection obj;
    final data = await _mnGeofenceLocationCollection.getById([id]);
    if (data.length != 0) {
      obj = GeofenceLocationCollection.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (GeofenceLocationCollection) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnGeofenceLocationCollection.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnGeofenceLocationCollection.update(this);
    }

    return id;
  }

  /// saveAs GeofenceLocationCollection. Returns a new Primary Key value of GeofenceLocationCollection

  /// <returns>Returns a new Primary Key value of GeofenceLocationCollection
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<GeofenceLocationCollection> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  Future<List<dynamic>> saveAll(
      List<GeofenceLocationCollection> geofencelocationcollections) async {
    // final results = _mnGeofenceLocationCollection.saveAll('INSERT OR REPLACE INTO geofenceLocationCollection (id,uuid, radius, latitude, longitude)  VALUES (?,?,?,?,?)',geofencelocationcollections);
    // return results; removed in sqfentity_gen 1.3.0+6
    DatabaseModel().batchStart();
    for (final obj in geofencelocationcollections) {
      await obj.save();
    }
    return DatabaseModel().batchCommit();
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnGeofenceLocationCollection.rawInsert(
              'INSERT OR REPLACE INTO geofenceLocationCollection (id,uuid, radius, latitude, longitude)  VALUES (?,?,?,?,?)',
              [id, uuid, radius, latitude, longitude]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage:
                'GeofenceLocationCollection id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'GeofenceLocationCollection id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage:
              'GeofenceLocationCollection Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<GeofenceLocationCollection>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(
      List<GeofenceLocationCollection> geofencelocationcollections) async {
    final results = await _mnGeofenceLocationCollection.rawInsertAll(
        'INSERT OR REPLACE INTO geofenceLocationCollection (id,uuid, radius, latitude, longitude)  VALUES (?,?,?,?,?)',
        geofencelocationcollections);
    return results;
  }

  /// Deletes GeofenceLocationCollection

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete GeofenceLocationCollection invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnGeofenceLocationCollection
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnGeofenceLocationCollection.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  GeofenceLocationCollectionFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return GeofenceLocationCollectionFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  GeofenceLocationCollectionFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return GeofenceLocationCollectionFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion geofencelocationcollection

// region GeofenceLocationCollectionField
class GeofenceLocationCollectionField extends SearchCriteria {
  GeofenceLocationCollectionField(this.geofencelocationcollectionFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  GeofenceLocationCollectionFilterBuilder geofencelocationcollectionFB;

  GeofenceLocationCollectionField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  GeofenceLocationCollectionFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.EQuals, geofencelocationcollectionFB._addedBlocks)
        : setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.NotEQuals, geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.EQualsOrNull, geofencelocationcollectionFB._addedBlocks)
        : setCriteria(
            pValue,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.NotEQualsOrNull,
            geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder isNull() {
    geofencelocationcollectionFB._addedBlocks = setCriteria(
        0,
        geofencelocationcollectionFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      geofencelocationcollectionFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          geofencelocationcollectionFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          geofencelocationcollectionFB._addedBlocks);
      _waitingNot = '';
      geofencelocationcollectionFB._addedBlocks
              .needEndBlock[geofencelocationcollectionFB._blockIndex] =
          geofencelocationcollectionFB._addedBlocks.retVal;
    }
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      geofencelocationcollectionFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          geofencelocationcollectionFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          geofencelocationcollectionFB._addedBlocks);
      _waitingNot = '';
      geofencelocationcollectionFB._addedBlocks
              .needEndBlock[geofencelocationcollectionFB._blockIndex] =
          geofencelocationcollectionFB._addedBlocks.retVal;
      geofencelocationcollectionFB._addedBlocks
              .needEndBlock[geofencelocationcollectionFB._blockIndex] =
          geofencelocationcollectionFB._addedBlocks.retVal;
    }
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      geofencelocationcollectionFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          geofencelocationcollectionFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          geofencelocationcollectionFB._addedBlocks);
      _waitingNot = '';
      geofencelocationcollectionFB._addedBlocks
              .needEndBlock[geofencelocationcollectionFB._blockIndex] =
          geofencelocationcollectionFB._addedBlocks.retVal;
    }
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder between(
      dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      geofencelocationcollectionFB._addedBlocks = setCriteria(
          pFirst,
          geofencelocationcollectionFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          geofencelocationcollectionFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        geofencelocationcollectionFB._addedBlocks = setCriteria(
            pFirst,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.LessThan,
            geofencelocationcollectionFB._addedBlocks);
      } else {
        geofencelocationcollectionFB._addedBlocks = setCriteria(
            pFirst,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            geofencelocationcollectionFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        geofencelocationcollectionFB._addedBlocks = setCriteria(
            pLast,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.GreaterThan,
            geofencelocationcollectionFB._addedBlocks);
      } else {
        geofencelocationcollectionFB._addedBlocks = setCriteria(
            pLast,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            geofencelocationcollectionFB._addedBlocks);
      }
    }
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.GreaterThan, geofencelocationcollectionFB._addedBlocks)
        : setCriteria(
            pValue,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.LessThan, geofencelocationcollectionFB._addedBlocks)
        : setCriteria(
            pValue,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(
            pValue,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            geofencelocationcollectionFB._addedBlocks)
        : setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.LessThan, geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    geofencelocationcollectionFB._addedBlocks = _waitingNot == ''
        ? setCriteria(
            pValue,
            geofencelocationcollectionFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            geofencelocationcollectionFB._addedBlocks)
        : setCriteria(pValue, geofencelocationcollectionFB.parameters, param,
            SqlSyntax.GreaterThan, geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }

  GeofenceLocationCollectionFilterBuilder inValues(dynamic pValue) {
    geofencelocationcollectionFB._addedBlocks = setCriteria(
        pValue,
        geofencelocationcollectionFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        geofencelocationcollectionFB._addedBlocks);
    _waitingNot = '';
    geofencelocationcollectionFB._addedBlocks
            .needEndBlock[geofencelocationcollectionFB._blockIndex] =
        geofencelocationcollectionFB._addedBlocks.retVal;
    return geofencelocationcollectionFB;
  }
}
// endregion GeofenceLocationCollectionField

// region GeofenceLocationCollectionFilterBuilder
class GeofenceLocationCollectionFilterBuilder extends SearchCriteria {
  GeofenceLocationCollectionFilterBuilder(GeofenceLocationCollection obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  GeofenceLocationCollection _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  GeofenceLocationCollectionFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  GeofenceLocationCollectionFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  GeofenceLocationCollectionFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  GeofenceLocationCollectionFilterBuilder where(String whereCriteria,
      {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param =
          DbParameter(columnName: parameterValue == null ? null : '');
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  GeofenceLocationCollectionFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  GeofenceLocationCollectionFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  GeofenceLocationCollectionFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  GeofenceLocationCollectionFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  GeofenceLocationCollectionFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  GeofenceLocationCollectionFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  GeofenceLocationCollectionField setField(
      GeofenceLocationCollectionField field, String colName, DbType dbtype) {
    return GeofenceLocationCollectionField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  GeofenceLocationCollectionField _id;
  GeofenceLocationCollectionField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  GeofenceLocationCollectionField _uuid;
  GeofenceLocationCollectionField get uuid {
    return _uuid = setField(_uuid, 'uuid', DbType.text);
  }

  GeofenceLocationCollectionField _radius;
  GeofenceLocationCollectionField get radius {
    return _radius = setField(_radius, 'radius', DbType.real);
  }

  GeofenceLocationCollectionField _latitude;
  GeofenceLocationCollectionField get latitude {
    return _latitude = setField(_latitude, 'latitude', DbType.real);
  }

  GeofenceLocationCollectionField _longitude;
  GeofenceLocationCollectionField get longitude {
    return _longitude = setField(_longitude, 'longitude', DbType.real);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (GeofenceLocationCollection._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<GeofenceLocationCollection> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (GeofenceLocationCollection._softDeleteActivated && !hardDelete) {
      r = await _obj._mnGeofenceLocationCollection
          .updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnGeofenceLocationCollection.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from geofenceLocationCollection ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnGeofenceLocationCollection.updateBatch(qparams, values);
  }

  /// This method always returns GeofenceLocationCollection Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<GeofenceLocationCollection>
  Future<GeofenceLocationCollection> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnGeofenceLocationCollection.toList(qparams);
    final data = await objFuture;
    GeofenceLocationCollection obj;
    if (data.isNotEmpty) {
      obj = GeofenceLocationCollection.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int.
  ///
  /// <returns>int
  Future<int> toCount(
      [VoidCallback Function(int c) geofencelocationcollectionCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final geofencelocationcollectionsFuture =
        await _obj._mnGeofenceLocationCollection.toList(qparams);
    final int count = geofencelocationcollectionsFuture[0]['CNT'] as int;
    if (geofencelocationcollectionCount != null) {
      geofencelocationcollectionCount(count);
    }
    return count;
  }

  /// This method returns List<GeofenceLocationCollection>.
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<GeofenceLocationCollection>
  Future<List<GeofenceLocationCollection>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<GeofenceLocationCollection> geofencelocationcollectionsData =
        await GeofenceLocationCollection.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return geofencelocationcollectionsData;
  }

  /// This method returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnGeofenceLocationCollection.toList(qparams);
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnGeofenceLocationCollection.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnGeofenceLocationCollection.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await GeofenceLocationCollection.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnGeofenceLocationCollection.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion GeofenceLocationCollectionFilterBuilder

// region GeofenceLocationCollectionFields
class GeofenceLocationCollectionFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fUuid;
  static TableField get uuid {
    return _fUuid = _fUuid ?? SqlSyntax.setField(_fUuid, 'uuid', DbType.text);
  }

  static TableField _fRadius;
  static TableField get radius {
    return _fRadius =
        _fRadius ?? SqlSyntax.setField(_fRadius, 'radius', DbType.real);
  }

  static TableField _fLatitude;
  static TableField get latitude {
    return _fLatitude =
        _fLatitude ?? SqlSyntax.setField(_fLatitude, 'latitude', DbType.real);
  }

  static TableField _fLongitude;
  static TableField get longitude {
    return _fLongitude = _fLongitude ??
        SqlSyntax.setField(_fLongitude, 'longitude', DbType.real);
  }
}
// endregion GeofenceLocationCollectionFields

//region GeofenceLocationCollectionManager
class GeofenceLocationCollectionManager extends SqfEntityProvider {
  GeofenceLocationCollectionManager()
      : super(DatabaseModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'geofenceLocationCollection';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion GeofenceLocationCollectionManager
class DatabaseModelSequenceManager extends SqfEntityProvider {
  DatabaseModelSequenceManager() : super(DatabaseModel());
}
// END OF ENTITIES
